/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.nashss.se.clientkeeper;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void appGreetingMessageIsCorrect() {
        App classUnderTest = new App();
        assertEquals("Hello World!", classUnderTest.getGreeting(), "Greeting should be 'Hello World!'");
    }

    @Test
    void mainMethodExecutesWithoutException() {
        try {
            App.main(new String[]{});
        } catch (Exception e) {
            fail("Main method should not throw an exception");
        }
    }
}
