/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.nashss.se.clientkeeper;


/**
 * Main application class for ClientKeeper.
 */
public class App {
    /**
     * Returns a greeting message.
     *
     * @return a greeting message as a String
     */
    public String getGreeting() {
        return "Hello World!";
    }

    /**
     * Main method that serves as the entry point of the application.
     *
     * @param args command-line arguments
     */
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
